### ISSUE TITLE
pnp4nagios

### ISSUE THREAD

**Issue by antonzhelyazkov** [Napsty/check_netio#13]
Hello,

I am looking for php4nagios plugin for this script?

**Comment by Napsty** [comment]
You can do your own pnp4nagios templates based on the plugin output, see https://www.claudiokuenzler.com/blog/684/creating-custom-pnp4nagios-templates-commands-icinga2-nrpe-checks for example.
Closing this issue here because pnp4nagios is out of scope of the plugin.
