### ISSUE TITLE
[Question] Register TCP connection aborts with this?

### ISSUE THREAD

**Issue by MarcusCaepio** [Napsty/check_netio#8]
Hi Claudio, 
I just got a question and I cannot find another way to ask you.
Is it possible to register tcp connection aborts and reconnects with this plugin?
I have to check, if connections from one network to another are stable or have aborts after a couple of time. 

Thanks and have a nice weekend,
Marcus

**Comment by Napsty** [comment]
You could use the `-t` parameter to include system-wide tcp statistics into the plugin's performance data. There is currently no possibility to use thresholds on these stats. However if the counters increase and you use (for example) Grafana, you could set up a Grafana trigger/alert.

**Comment by MarcusCaepio** [comment]
Thanks a lot. Indeed, I use influxdb+grafana. Are you interested in expand this plugin for e.g. checking TCPAborts ?

**Comment by Napsty** [comment]
Yeah why not. Right now TCPAborts can be read from the tcp stats and show up in perf data:

```
TCPAbortOnData=1363337089;;;; TCPAbortOnClose=104580;;;; TCPAbortOnMemory=0;;;; TCPAbortOnTimeout=11042;;;; TCPAbortOnLinger=0;;;; TCPAbortFailed=0;;;;
```

What are you suggesting? To do specific checks on certain tcp stats with thresholds? Or use the same method as `-e` is doing with interface errors?

**Comment by MarcusCaepio** [comment]
Good Question... Right now, I am not 100% sure, what all the TCPAbort metrics mean, which are critical, what is normal etc. Do you know more about this, than me? ^^ Basically I would say, (a) specific check(s) with thresholds? Maybe sth. like "-a" for "aborted" instead of -e ?

**Comment by MarcusCaepio** [comment]
Hey,
I let netio run on a few hosts over the weekend. Are the TCPAborts just counted since the last reboot? If yes, I think, a delta between the checks would be better, to see current problems for a specific time. What do you think?

**Comment by Napsty** [comment]
Correct, the counters are since boot time. What graphing solution do you use? If you use Grafana, you should be able to see the diffs if you use a derivative handling of the stats:

 
![image](https://user-images.githubusercontent.com/3702203/136920080-7e3d1c07-45e5-45ec-ac0f-bd53dcaa7e22.png)

edit: just saw you mentioned Grafana above '^^
